In [ ]:
pip install neurolab

     |████████████████████████████████| 655kB 3.3MB/s 
  Created wheel for neurolab: filename=neurolab-0.3.5-cp36-none-any.whl size=22181 sha256=f49fe372fa4028b0fc984104a353a2dd8c65d375304e077011c252b2df2c2b78
  Stored in directory: /root/.cache/pip/wheels/c6/8f/37/32ab1cf4d601dc0bc49d7241012a4292db4b343bebff5b68e6
Successfully built neurolab


In [ ]:
pip install neupy

     |████████████████████████████████| 235kB 3.3MB/s 
     |████████████████████████████████| 92.6MB 43kB/s 
     |████████████████████████████████| 368kB 47.7MB/s 
     |████████████████████████████████| 3.2MB 47.3MB/s 
     |████████████████████████████████| 51kB 6.3MB/s 
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: tensorflow 2.3.0
    Uninstalling tensorflow-2.3.0:
      Successfully uninstalled tensorflow-2.3.0
  Found existing installation: progressbar2 3.38.0
    Uninstalling progressbar2-3.38.0:
      Successfully uninstalled progressbar2-3.38.0
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [28]:
import numpy as np

# train_lvq: trains an lvq system using the given training data and
# corresponding labels. Run the desired number of epochs using the
# given learning rate. Optional validation set to monitor performance.
def train_lvq(data, labels, num_epochs, learning_rate, validation_data=None, validation_labels=None):
    # Get unique class labels.
    num_dims = data.shape[1]
    labels = labels.astype(int)
    unique_labels = list(set(labels))

    # Initialize prototypes using class means.
    num_protos = len(unique_labels)
    prototypes = np.empty((num_protos, num_dims))
    proto_labels = []
    prototypes = np.array([[5.1, 3.5, 1.4, 0.2],[7.0, 3.2, 4.7, 1.4],[6.3, 3.3, 6.0, 2.5]])
    proto_labels = np.array([1,2,3])

    # Loop through data set.
    learning_rate_new = learning_rate
    for epoch in range(0, num_epochs):
        print("Epoch : ", epoch+1)
        print("Learning Rate : ", learning_rate_new, "\n")
        count = 1;
        for fvec, lbl in zip(data, labels):
            #As Counting
            print("Data", count, ": ")
            count+=1;

            print("Bobot Awal : \n", prototypes, "\n")
            # Compute distance from each prototype to this point
            distances = list(np.sqrt(np.sum(np.subtract(fvec, p)**2)) for p in prototypes)
            print("Jarak ke vektor bobot 1 : ", distances[0])
            print("Jarak ke vektor bobot 2 : ", distances[1])
            min_dist_index = distances.index(min(distances))

            # Determine winner prototype.
            winner = prototypes[min_dist_index]
            winner_label = proto_labels[min_dist_index]

            # Push or repel the prototype based on the label.
            if winner_label == lbl:
                sign = 1
            else:
                sign = -1

            # Update winner prototype
            prototypes[min_dist_index] = np.add(prototypes[min_dist_index], np.subtract(fvec, winner) * learning_rate_new * sign)
            print("Kelas pemenang : ",min_dist_index+1,"\n")
            print("Bobot baru ",min_dist_index+1," : ", prototypes[min_dist_index], "\n")
        learning_rate_new = learning_rate_new - learning_rate_new*0.1
        print("\n\n")
    
    print("Bobot Akhir :")
    return (prototypes, proto_labels)

In [29]:
#Inisialisasi dataset dan labels
data = np.genfromtxt(r'iris.csv',delimiter=';')
labels = np.genfromtxt(r'iris_labels.csv',delimiter=';')
train_lvq(data, labels, num_epochs=3, learning_rate=0.1)

Epoch :  1
Learning Rate :  0.1 

Data 1 : 
Bobot Awal : 
 [[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]] 

Jarak ke vektor bobot 1 :  0.5385164807134502
Jarak ke vektor bobot 2 :  4.096339829652808
Kelas pemenang :  1 

Bobot baru  1  :  [5.08 3.45 1.4  0.2 ] 

Data 2 : 
Bobot Awal : 
 [[5.08 3.45 1.4  0.2 ]
 [7.   3.2  4.7  1.4 ]
 [6.3  3.3  6.   2.5 ]] 

Jarak ke vektor bobot 1 :  0.4657252408878006
Jarak ke vektor bobot 2 :  4.27668095606862
Kelas pemenang :  1 

Bobot baru  1  :  [5.042 3.425 1.39  0.2  ] 

Data 3 : 
Bobot Awal : 
 [[5.042 3.425 1.39  0.2  ]
 [7.    3.2   4.7   1.4  ]
 [6.3   3.3   6.    2.5  ]] 

Jarak ke vektor bobot 1 :  0.559543563987649
Jarak ke vektor bobot 2 :  4.177319714841086
Kelas pemenang :  1 

Bobot baru  1  :  [4.9978 3.3925 1.401  0.2   ] 

Data 4 : 
Bobot Awal : 
 [[4.9978 3.3925 1.401  0.2   ]
 [7.     3.2    4.7    1.4   ]
 [6.3    3.3    6.     2.5   ]] 

Jarak ke vektor bobot 1 :  0.2075140718120099
Jarak ke vektor bobot 2 :  4.0607

(array([[5.15391313, 3.55624398, 1.46469489, 0.24672142],
        [6.03421574, 2.80291496, 3.82263125, 1.04251937],
        [6.85405629, 3.03395299, 5.8879436 , 2.13242263]]), array([1, 2, 3]))

In [35]:
#Testing LVQ
import math as mt
def test_data(weight_lvq, data_test):
    print(weight_lvq)
    comparison_mat = []
    cl_A = 0
    cl_B = 0
    cl_C = 0
    for q in range(len(data_test)):
        for g in range(len(weight_lvq)):
            for w in range(len(weight_lvq[g]) - 1):
                cl_A += (data_test[q][w] - weight_lvq[0][w])
                cl_B += (data_test[q][w] - weight_lvq[1][w])
                cl_C += (data_test[q][w] - weight_lvq[2][w])
                w += 1
            g += 1
        plant_class = data_test[q][4]
        xw1 = mt.sqrt(cl_A ** 2)
        xw2 = mt.sqrt(cl_B ** 2)
        xw3 = mt.sqrt(cl_C ** 2)
        res = np.array([xw1, xw2, xw3])
        val = np.amin(res)
        if(val == xw1):
            tanaman_type = "IRIS SETOSA"
            winner = weight_lvq[0]
        elif (val == xw2):
            tanaman_type = "IRIS VESICOLOR"
            winner = weight_lvq[1]
        elif (val == xw3):
            tanaman_type = "IRIS VIRGINICA"
            winner = weight_lvq[2]
        print("Plant Type " + str(q + 1)+" = "+tanaman_type+".")
        result = [plant_class,winner[4]]
        comparison_mat.append(result)
        q++1
    right=0
    wrong=0
    for x in range(len(comparison_mat)):
            if(comparison_mat[x][0]==comparison_mat[x][1]):
                right+=1
            else:
                wrong+=1
    print("Models Accuracy = "+ str((float(right)/(right+wrong))*100) +"%")

In [37]:
#Inisialisasi Testing
weight_lvq = np.genfromtxt(r'iris_wight.csv',delimiter=';')
data_test = np.genfromtxt(r'iris_test.csv',delimiter=';')
test_data(weight_lvq, data_test)

[[5.15391313 3.55624398 1.46469489 0.24672142 1.        ]
 [6.03421574 2.80291496 3.82263125 1.04251937 2.        ]
 [6.85405629 3.03395299 5.8879436  2.13242263 3.        ]]
Plant Type 1 = IRIS SETOSA.
Plant Type 2 = IRIS SETOSA.
Plant Type 3 = IRIS SETOSA.
Plant Type 4 = IRIS SETOSA.
Plant Type 5 = IRIS SETOSA.
Plant Type 6 = IRIS SETOSA.
Plant Type 7 = IRIS SETOSA.
Plant Type 8 = IRIS SETOSA.
Plant Type 9 = IRIS SETOSA.
Plant Type 10 = IRIS SETOSA.
Plant Type 11 = IRIS SETOSA.
Plant Type 12 = IRIS SETOSA.
Plant Type 13 = IRIS SETOSA.
Plant Type 14 = IRIS SETOSA.
Plant Type 15 = IRIS SETOSA.
Plant Type 16 = IRIS SETOSA.
Plant Type 17 = IRIS SETOSA.
Plant Type 18 = IRIS SETOSA.
Plant Type 19 = IRIS SETOSA.
Plant Type 20 = IRIS SETOSA.
Plant Type 21 = IRIS SETOSA.
Plant Type 22 = IRIS SETOSA.
Plant Type 23 = IRIS SETOSA.
Plant Type 24 = IRIS SETOSA.
Plant Type 25 = IRIS SETOSA.
Plant Type 26 = IRIS SETOSA.
Plant Type 27 = IRIS SETOSA.
Plant Type 28 = IRIS SETOSA.
Plant Type 29 = IRIS S